adaptive-controller-config:
  densification-view-space-position-gradients-threshold: 0.0000015
  gaussian-split-factor-phi: 1.6
  num-iterations-densify: 100
  num-iterations-reset-alpha: 3000
  num-iterations-warm-up: 1000
  reset-alpha-value: -0.2
  transparent-alpha-threshold: -0.2
  under-reconstructed-s-threshold: 0.05
  floater_threshold: 3.0
gaussian-point-cloud-scene-config:
  max-num-points-ratio: 3.0
  num-of-features: 56
increase-color-max-sh-band-interval: 1000.0
log-image-interval: 1000
log-loss-interval: 10
log-metrics-interval: 100
loss-function-config:
  lambda-value: 0.2
num-iterations: 300000
pointcloud-parquet-path: 'data/boots/point_cloud.parquet'
rasterisation-config:
  depth-to-sort-key-scale: 100.0
  far-plane: 1000.0
  near-plane: 0.001
summary-writer-log-dir: logs/boots_base
train-dataset-json-path: 'data/boots/boots_train.json'
val-dataset-json-path: 'data/boots/boots_val.json'
val-interval: 1000
