adaptive-controller-config:
  densification-view-space-position-gradients-threshold: 0.0000008
  gaussian-split-factor-phi: 1.6
  num-iterations-densify: 100
  num-iterations-reset-alpha: 8000
  num-iterations-warm-up: 1000
  reset-alpha-value: -2.0
  transparent-alpha-threshold: -2.
  under-reconstructed-s-threshold: 0.8
  floater_threshold: 5.0
gaussian-point-cloud-scene-config:
  max-num-points-ratio: 2.0
  num-of-features: 56
increase-color-max-sh-band-interval: 1000.0
log-image-interval: 1000
log-loss-interval: 10
log-metrics-interval: 100
enable_taichi_kernel_profiler: True
log_taichi_kernel_profile_interval: 3000
feature_learning_rate: 0.01
position_learning_rate: 0.0001
loss-function-config:
  lambda-value: 0.2
  enable_regularization: True
  regularization_weight: 0.1
num-iterations: 300000
pointcloud-parquet-path: 'data/kitti/point_cloud.parquet'
rasterisation-config:
  depth-to-sort-key-scale: 100.0
  far-plane: 1000.0
  near-plane: 1.0
summary-writer-log-dir: logs/kitti_base
train-dataset-json-path: 'data/kitti/kitti_train.json'
val-dataset-json-path: 'data/kitti/kitti_val.json'
val-interval: 5000
